services:
  ja-hello-world:
    hostname: ja-hello-world
    image: 'ccr.ccs.tencentyun.com/a2cd/ja-hello-world:latest'
    container_name: ja-hello-world
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - ACTIVE_PROFILES=prd
      - VM_OPTS=-server -Xms64m -Xmx128m
    networks:
      - main

networks:
  main:
    external: true
