name: Java CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_GREETING: hello
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: '5'
  REGISTRY: ${{ secrets.REGISTRY_DOMAIN }}
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  JASYPT_PASSWORD: ${{ secrets.JASYPT_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # pull代码
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle' # gradle, maven, sbt
      - name: Run build src
        run: |
          chmod +x ./gradlew && ./gradlew clean bootJar
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_DOMAIN }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Run Build and push docker image
        env:
          NAMESPACE: a2cd
          IMAGE_NAME: ja-hello-world
          IMAGE_TAG: latest
        run: |
          docker build --build-arg ARG_JASYPT_PASSWORD=$JASYPT_PASSWORD -t $REGISTRY/$NAMESPACE/$IMAGE_NAME:$IMAGE_TAG .
          docker push $REGISTRY/$NAMESPACE/$IMAGE_NAME:$IMAGE_TAG
      - name: Setup SSH
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          KEY_FILE: a2cd.key # 不能用~/.ssh/a2cd.key作为value
        run: |
          mkdir -p ~/.ssh/ && echo "$SSH_PRIVATE_KEY" > ~/.ssh/$KEY_FILE && chmod 600 ~/.ssh/$KEY_FILE
          cat >> ~/.ssh/config <<END
          Host a2cd
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/$KEY_FILE
            StrictHostKeyChecking no
          END
      - name: Run deploy
        run: ssh a2cd 'cd /usr/local/repo/ja-hello-world/ && git pull origin main && docker-compose pull && docker-compose up -d'
